create USER TIMES_user identified by systemsss;
grant all privileges to times_user;

CREATE TABLE PROJECT_CODE_MST (
	PROJECT_CODE VARCHAR2(50) PRIMARY KEY,
	PROJECT_NAME VARCHAR2(50)
);

CREATE TABLE TASK_CODE_MST(
	TASK_CODE VARCHAR2(50) PRIMARY KEY,
	TASK_NAME VARCHAR2(50)
);

CREATE SEQUENCE SEQ_TASK_ID START WITH 1 NOCACHE;

CREATE TABLE TASK_INFO(

	TASK_INFO_ID NUMBER(9) PRIMARY KEY,
	USER_ID CHAR(6)NOT NULL,
  ATTENDED_DATE CHAR(10)NOT NULL,
	START_TIME CHAR(5),
	END_TIME CHAR(5),
	TASK_HOURS NUMBER(3,1),
	PROJECT_CODE VARCHAR2(50) REFERENCES PROJECT_CODE_MST(PROJECT_CODE),
	TASK_CODE VARCHAR2(50) REFERENCES TASK_CODE_MST(TASK_CODE),
	TASK_DESCRIPTION VARCHAR2(75)
);
CREATE UNIQUE INDEX task_info_index ON TASK_INFO (USER_ID, ATTENDED_DATE, PROJECT_CODE, TASK_CODE);



commit;





