INSERT INTO PROJECT_CODE_MST VALUES('TRAINING','研修');
INSERT INTO PROJECT_CODE_MST VALUES('REST','休憩');
INSERT INTO PROJECT_CODE_MST VALUES('projABC','ABCプロジェクト');
INSERT INTO PROJECT_CODE_MST VALUES('projXYZ','XYZプロジェクト');

INSERT INTO TASK_CODE_MST VALUES('PROG','プログラミング');
INSERT INTO TASK_CODE_MST VALUES('STUDY','学習');
INSERT INTO TASK_CODE_MST VALUES('SPEC_DESIGN','詳細設計');
INSERT INTO TASK_CODE_MST VALUES('UNITTEST','単体テスト');
INSERT INTO TASK_CODE_MST VALUES('PAIDLEAVE','有給休暇');
INSERT INTO TASK_CODE_MST VALUES('OTHERS','その他');


INSERT INTO TASK_INFO (TASK_INFO_Id,USER_ID,ATTENDED_DATE,PROJECT_CODE,TASK_CODE) VALUES
(SEQ_TASK_ID.NEXTVAL,'test','2019-03-24','REST','OTHERS');
INSERT INTO TASK_INFO (TASK_INFO_Id,USER_ID,ATTENDED_DATE,PROJECT_CODE,TASK_CODE) VALUES
(SEQ_TASK_ID.NEXTVAL,'test','2019-03-25','projABC','SPEC_DESIGN');
INSERT INTO TASK_INFO VALUES
(SEQ_TASK_ID.NEXTVAL,'test','2019-03-25','10:30','15:30',5,'projABC','PROG','モジュール1作成');
INSERT INTO TASK_INFO VALUES
(SEQ_TASK_ID.NEXTVAL,'test','2019-03-26','8:00','12:00',NULL,'REST','OTHERS','午前半休');
INSERT INTO TASK_INFO VALUES
(SEQ_TASK_ID.NEXTVAL,'test','2019-03-26','13:00','17:00',4,'projXYZ','PROG',NULL);
INSERT INTO TASK_INFO VALUES
(SEQ_TASK_ID.NEXTVAL,'test','2019-03-27','10:00','17:30',7.5,'projXYZ','UNITTEST','1234');

COMMIT;